name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_ENDPOINT: ${{ secrets.LANGCHAIN_PROJECT }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_PROJECT }}
      LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
      OPENAI_API_KEY: ${{ secrets.API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Clone external repository
      run: git clone https://github.com/karttofer/vnzlahistory-sper.git
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f vnzlahistory-sper/requirements.txt ]; then pip install -r vnzlahistory-sper/requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 vnzlahistory-sper --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 vnzlahistory-sper --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python vnzlahistory-sper/main.py  # Asegúrate de que el archivo main.py está en la ruta correcta
